### ISSUE TITLE
Outated library on maven

### ISSUE THREAD

**Issue by AlexITC** [bitsoex/bitso-java#30]
The current released version (3.0.3) allows to use two books only (BTC_MXN, ETH_MXN) and its leading to exceptions while calling `Bitso#availableBooks`.

The current code on master doesn't have that limitation.

When can we expect the current code released to maven?

**Comment by AlexITC** [comment]
@vogelito do you have any idea about this? current version is broken and I would like to use the SDK.

**Comment by nvcruzhe** [comment]
Hi Alex, we will update the library soon Sorry for the inconvenience.

**Comment by AlexITC** [comment]
The updated library is now in JitPack, thanks!

**Comment by vogelito** [comment]
Thanks for your patience @AlexITC and apologies for the delays. Let us know what you're building!
