### ISSUE TITLE
Bitso#getAccountStatus() does not work against dev server

### ISSUE THREAD

**Issue by franz-see** [bitsoex/bitso-java#35]
Given the following

    boolean production= true;
    Bitso bitso = new Bitso(System.getenv("BITSO_API_KEY"), System.getenv("BITSO_API_SECRET"), 1, true, production);
    BitsoAccountStatus accountStatus = bitso.getAccountStatus();
    assertNotNull(accountStatus);

This works. But if set `production` to `false` using the same API KEY and SECRET, it results to a `com.bitso.exceptions.BitsoAPIException: Invalid Nonce or Invalid Credentials`

Kindly advice.

Thanks,
Franz

**Comment by vogelito** [comment]
Hi @franz-see - is the API KEY and SECRET you are using created in our dev environment?

**Comment by franz-see** [comment]
I created the API  Key and Secret from this page - https://bitso.com/api_setup

There is no indication for the environment when i created the key and secret.

If there's a different page or a different mechanism for generating key and secret for the dev environment, kindly advice. 

Thanks,
Franz

**Comment by nvcruzhe** [comment]
@franz-see please go to this page: https://dev.bitso.com
Create an account and follow the same process you have followed on the production web page for creating your keys. If you need to get some test money ping us.

**Comment by franz-see** [comment]
@VictorCruzIsc excellent! thanks, i'll do that.

**Comment by franz-see** [comment]
@VictorCruzIsc Sorry. I tried registering but I did not get an email for the verification link. And I need that to login. How do I request that to be re-sent?

**Comment by vogelito** [comment]
@metoro - seems like dev emails are somehow broken and @franz-see can't verify his account.

**Comment by nvcruzhe** [comment]
@franz-see can you please give me your user id? in order to re send the verification link...

**Comment by nvcruzhe** [comment]
@franz-see were you able to verify your account?

**Comment by franz-see** [comment]
@vogelito @nvcruzhe FYI : im now able to register and i can now receive the verification email. Apologies for the late verifications and thanks for the comments!

**Comment by vogelito** [comment]
Great, happy to hear that @franz-see. Closing this issue for now then.
