### ISSUE TITLE
Test funds

### ISSUE THREAD

**Issue by zackulrichAC** [bitsoex/bitso-java#38]
Hi I'm trying to get some testnet bitcoins into my dev.bitso.com account, but they're all stuck in "Pending" anyway someone can help me?

**Comment by trailtacos** [comment]
Hi @zackulrichAC,

Your deposits should now be available in dev.bitso.com. Unfortunately confirmation is not automatic for the testnet in that environment currently. Apologies for the inconvenience.

Regards

Crispin
