### ISSUE TITLE
Fondeo por Testnet pendiente 

### ISSUE THREAD

**Issue by luischavez** [bitsoex/bitso-java#39]
Acabo de realizar un fondeo a mi cuenta en dev.bitso.com mediante Testnet pero sigue pendiente, en el blockchain ya marca 6 confirmaciones:
[https://testnet.blockchain.info/tx/752b0ab40ac9202f0f3ff98de50642289f3cba98398bcb814d102844a02a31c7](https://testnet.blockchain.info/tx/752b0ab40ac9202f0f3ff98de50642289f3cba98398bcb814d102844a02a31c7)

**Comment by nvcruzhe** [comment]
@luischavez tu fondeo ya fue procesado.
