### ISSUE TITLE
Invalid precision on place order with 8 decimals price

### ISSUE THREAD

**Issue by luischavez** [bitsoex/bitso-java#40]
The page accepts a precision of 8 decimals, but in the api it only accepts maximum 6 decimals for the price.

**Comment by nvcruzhe** [comment]
@luischavez working on it. Please let me check and fix ASAP

**Comment by luischavez** [comment]
any news about this?

**Comment by nvcruzhe** [comment]
@luischavez could you please post an example of a request that is returning an error.
And what error API is returning?

Remember that for XRP the max decimals allowed is 6
